#!/usr/bin/env zsh

blend_name="heads"
blend_vers="0.4"
image_name="${blend_name}-${blend_vers}-${arch}"

MAKEOPTS="-j$(grep -c 'processor' /proc/cpuinfo)"
TAR_STAGE4=true
mkefi="yes"
efi_work="$R/efi-files"

kernel_heads_version="4.19"
kernel_heads_url="https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-${kernel_heads_version}.tar.xz"

rootfs_overlay="https://github.com/headslive/rootfs-overlay"

torsocks_version="master"
torsocks_url="https://git.torproject.org/torsocks.git"

tomb_version="v2.4"
tomb_url="https://github.com/dyne/tomb.git"

gtomb_version="master"
gtomb_url="https://git.parazyd.org/gtomb"

ttdnsd_version="master"
ttdnsd_url="https://git.torproject.org/ioerror/ttdnsd.git"

wmutils_version="master"
wmutils_url="https://github.com/wmutils/core"

tbb_version="8.0.3"
case $arch in
	amd64) aa="64";;
	i386)  aa="32";;
esac
tbb_url="https://www.torproject.org/dist/torbrowser/${tbb_version}/tor-browser-linux${aa}-${tbb_version}_en-US.tar.xz"

extra_packages=(
	firmware-linux-free
	grub-efi-${arch}
	grub-efi-ia32-bin
	xserver-xorg
	xserver-xorg-legacy
	xserver-xorg-input-synaptics
	xserver-xorg-input-libinput
	xinit
	sudo
	lxqt-sudo
	openrc
	eudev
	yad
	pinentry-gtk2
	awesome
	openbox
	lxpanel
	lximage-qt
	adwaita-icon-theme
	breeze-cursor-theme
	breeze-gtk-theme
	nitrogen
	laptop-detect

	alsa-utils
	pulseaudio
	pasystray

	zsh
	ferm
	tmux
	busybox-static
	cryptsetup
	curl
	openssh-client
	sshfs
	pax-utils
	paxctl
	rfkill
	acpi
	acpid
	acpi-support
	lm-sensors
	lsof
	strace
	fdisk
	acl
	gradm2

	gnupg2
	dirmngr
	gpa
	pcsc-tools
	htop
	p7zip
	ssss
	macchanger
	aircrack-ng
	reaver
	steghide
	qrencode
	firefox-esr

	tor
	nyx
	apt-transport-tor
	apt-transport-https
	tsocks
	torsocks
	htpdate
	obfs4proxy
	openvpn
	wicd

	lxterminal
	lxmusic
	leafpad
	abiword
	abiword-plugin-grammar
	gnumeric
	zathura
	gtkhash
	rng-tools
	hexchat
	hexchat-otr
	hexchat-perl
	hexchat-plugins
	hexchat-python3
	irssi
	net-tools
	dnsutils
	gimp
	thunderbird
	enigmail
	electrum
	pass
	keepassx
	inkscape
	audacity
	synaptic
	sacc
	mpv
	gnome-mpv
	youtube-dl
	tig
	imagemagick
	libnotify-bin
	dunst
	scrot
	pcmanfm
	#dunst
	mlocate
	miscfiles
	gettext
	arandr
	xclip
	i3lock
	ncdu
	whois
	connect-proxy
	proxychains
	mat
	pciutils
	usbutils
	xarchiver
	#onionshare
	udiskie

	gnuchess
	gnuchess-book
	xboard
	hasciicam
	exif

	bc
	autoconf
	automake
	build-essential
	flex
	libbison-dev
	libtool-bin
	libtool
	libevent-dev
	libssl-dev
	libgcrypt20-dev
	libseccomp-dev
	libx11-xcb-dev
	libxcb-util0-dev
	libelf-dev
	gcc-8-plugin-dev
	equivs
	debhelper
)

purge_packages=(
	openssh-server
	openssh-sftp-server
)

finalize_purge_packages=(
	at-spi2-core
	autoconf
	automake
	autotools-dev
	avahi-daemon
	cups-pk-helper
	debhelper
	easy-rsa
	geoclue-2.0
	gir1.2-polkit-1.0
	kwayland-data
	kwayland-integration
	lxqt-policykit
	lxqt-policykit-l10n
	modemmanager
	ntp
	opensc
	papirus-icon-theme
	packagekit
	packagekit-tools
	pcmanfm-qt
	pcmanfm-qt-l10n
	phantomjs
	rtkit
	system-config-printer
	system-config-printer-common
	system-config-printer-udev
	sysv-rc
	tasksel
	tasksel-data
	ttdnsd-dbgsym
	upower
	usb-modeswitch
	qdbus
	qt-at-spi
	scour
)
