#!/usr/bin/env zsh

blend_name="heads"
blend_vers="0.0"
image_name="${blend_name}-${blend_vers}-${arch}"

MAKEOPTS="-j$(grep -c 'processor' /proc/cpuinfo)"

kernel_heads_git="https://gogs.dyne.org/heads/linux-heads"

rootfs_overlay="https://gogs.dyne.org/heads/rootfs-overlay"

#ferm_version="v2.3.1"
#ferm_url="https://gogs.dyne.org/heads/ferm"

awesome_version="4.0"
awesome_url="https://github.com/awesomeWM/awesome/releases/download/v${awesome_version}/awesome-${awesome_version}.tar.bz2"

xcb_xrm_version="1.2"
xcb_xrm_url="https://github.com/Airblader/xcb-util-xrm/releases/download/v${xcb_xrm_version}/xcb-util-xrm-${xcb_xrm_version}.tar.bz2"

icecat_version="45.5.1"
icecat_url="https://ftp.gnu.org/gnu/gnuzilla/$icecat_version/icecat-${icecat_version}.en-US.linux-${earch}.tar.bz2"

tor_version="0.3.0.3-alpha"
tor_url="https://dist.torproject.org/tor-${tor_version}.tar.gz"

torsocks_version="v2.2.0"
torsocks_url="https://git.torproject.org/torsocks.git"

arm_version="1.4.5.0"
arm_url="https://www.atagar.com/arm/resources/static/arm-${arm_version}.tar.bz2"

gradm_version="3.1-201608131257"
gradm_url="https://dev.gentoo.org/~blueness/hardened-sources/gradm/gradm-${gradm_version}.tar.gz"

tomb_version="v2.3"
tomb_url="https://github.com/dyne/tomb.git"

gtomb_version="0.9"
gtomb_url="https://github.com/parazyd/gtomb.git"

electrum_version="2.7.18"
electrum_url="https://download.electrum.org/${electrum_version}/Electrum-${electrum_version}.tar.gz"

tinfoil_version="master"
tinfoil_url="https://github.com/dyne/tinfoil.git"


extra_packages+=(
	## desktop
	xserver-xorg
	xinit
	xfonts-terminus
	zenity
	pinentry-gtk2

	## system
	cryptsetup
	curl
	openssh-client
	sshfs
	pax-utils
	paxctl
	rfkill
	traceroute

	## utils
	apg
	gnupg2
	keychain
	wpagui
	openvpn
	htop
	p7zip
	ssss
	monkeysphere
	terminology
	macchanger
	aircrack-ng
	reaver
	leafpad
	surf
	qrencode
	steghide

	# electrum
	python-qt4
	python-pip

	## misc ## TODO: sort this out
	acpi
	acpid
	abiword
	evince
	hexchat
	psi-plus
	psi-plus-plugins
	feh
	gimp
	icedove
	enigmail
	keepassx
	pass
	vlc
	tig
	tabbed
	imagemagick
	libnotify-bin
	scrot
	adwaita-icon-theme
	murrine-themes
	#lxappearance
	pcmanfm
	mlocate
	miscfiles
	gettext
	arandr
	xclip
	i3lock # TODO: hotkey/menu
	compton
	ncdu
	whois
	nmap
	python-markdown
	python-passlib
	connect-proxy
	xarchiver

	bastet
	bsdgames
	cavezofphear
	curseofwar
	gnuchess
	xboard
	matanza
	nethack-console
	hasciicam
	jhead
	sox

	## dev
	idle-python2.7
	bc
	aufs-tools
	autoconf
	automake
	build-essential
	ncurses-dev
	flex
	libbison-dev
	libtool-bin
	libtool
	libevent-dev
	libssl-dev
	libgcrypt20
	libgcrypt20-dev
	libseccomp2
	libseccomp-dev
	### awesomewm
	cmake
	lua5.1
	liblua5.1.0-dev
	gir1.2-freedesktop
	gir1.2-pango-1.0
	libdbus-1-dev
	libgdk-pixbuf2.0-dev
	libcairo2-dev
	libxcb-cursor-dev
	libxcb-randr0-dev
	libxcb-xtest0-dev
	libxcb-xinerama0-dev
	libxcb-shape0-dev
	libxcb-util0-dev
	libxcb-keysyms1-dev
	libxcb-icccm4-dev
	libxcb-xkb-dev
	libxkbcommon-x11-dev
	libxkbcommon-dev
	libstartup-notification0-dev
	libxdg-basedir-dev
	lua-lgi-dev
	###
)

purge_packages=(
	openssh-server
	openssh-sftp-server
	rsyslog
)

finalize_purge_packages=(
	cmake
	autoconf
	automake
	flex
	libbison-dev
	policykit-1
	policykit-1-gnome
	consolekit
)
