#!/bin/sh
# heads live - copyright 2017-2018 Ivan J. <parazyd@dyne.org>
# See https://www.gnu.org/licenses for license details (GPL-3)

rescue_shell() {
	echo "$@"
	echo " * Dropping to a shell."
	exec /bin/sh
}

mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys

grep -q 'debuginitramfs' /proc/cmdline && {
	rescue_shell "* Requested initramfs debug"
}

# Settle down devices. The USB drive sometimes doesn't come up fast
# enough, therefore, we need to wait a few seconds.
sleep 3

# First check if we have booted from a cd, otherwise it's probably
# a usb drive
for i in /dev/sr* /dev/sd* ; do
	mount -t iso9660 "$i" /mnt/root || continue
	[ -f /mnt/root/live/filesystem.squashfs ] && {
		echo " * found squashfs on $i"
		mounted="$i"
		break
	}
	umount /mnt/root
done

# We failed mounting a live medium
[ -n "$mounted" ] || rescue_shell \
"We have not managed to find a live medium.
Please investigate the environment, save the dmesg and file a bug
report along with it."

mkdir -p /mnt/ro
mkdir -p /mnt/rw
mkdir -p /mnt/overlay

echo " * mounting squashfs"
mount -t squashfs -o ro,noatime \
	/mnt/root/live/filesystem.squashfs /mnt/ro || rescue_shell

# Decide the tmpfs size
ram_amnt="$(free -m | awk '/^Mem: / {print $2}')"
tmp_amnt="$(( $ram_amnt / 2 / 1000 ))"
tmpfsje=512M
if  [ "$tmp_amnt" -gt 16000 ]; then tmpfsje=16G;
elif [ "$tmp_amnt" -gt 8000 ]; then tmpfsje=8G;
elif [ "$tmp_amnt" -gt 6000 ]; then tmpfsje=6G;
elif [ "$tmp_amnt" -gt 4000 ]; then tmpfsje=4G;
elif [ "$tmp_amnt" -gt 2000 ]; then tmpfsje=2G;
elif [ "$tmp_amnt" -gt 1000 ]; then tmpfsje=1G;
fi

echo " * mounting tmpfs"
mount -t tmpfs none -o size=$tmpfsje /mnt/rw || rescue_shell
mkdir /mnt/rw/upper
mkdir /mnt/rw/work

echo " * mounting overlayfs"
mount -t overlay \
	-o lowerdir=/mnt/ro,upperdir=/mnt/rw/upper,workdir=/mnt/rw/work \
	overlay /mnt/overlay || rescue_shell

echo "$mounted" > /mnt/overlay/usr/src/permakey/usbdev

mount --move /dev /mnt/overlay/dev || rescue_shell
umount /proc /sys
echo " * switching root"
exec switch_root /mnt/overlay /sbin/init || rescue_shell
